include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    prefer_final_locals: true
    always_declare_return_types: true
    avoid_null_checks_in_equality_operators: true
    avoid_types_on_closure_parameters: true
    avoid_print: true
    prefer_single_quotes: true
    prefer_is_empty: true
    unnecessary_this: true
    always_use_package_imports: true
    prefer_typing_uninitialized_variables: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    empty_statements: true
    unnecessary_lambdas: true
    avoid_empty_else: true
    prefer_function_declarations_over_variables: true
    avoid_function_literals_in_foreach_calls: true
    avoid_renaming_method_parameters: true
    avoid_shadowing_type_parameters: true
    avoid_private_typedef_functions: true