name: task_management
description: "A new Flutter project."

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # base
  dartz: ^0.10.1
  logger: ^2.4.0
  get: ^4.6.6
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  # dio_cache_interceptor_hive_store: ^3.2.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0

  # ui
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - .env